[package]
url = "https://gitlab.gnome.org/GNOME/gtk-doc.git"
ref = "1.35.1"
depth = 1

[[build_configs]]
build_system = "meson"
build_tools = ["python3:pygments"]
dev_dependencies = ["itstool@2.0.7","gettext@0.25", "libxslt@1.1.42"]