[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxext.git"
ref = "libXext-1.3.6"
depth = 1

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
envs = ["xorg_cv_malloc0_returns_null=yes"]
dependencies = ["libice@1.1.2", "libx11@1.8.11"]
dev_dependencies = ["macros@1.20.2"]

# Note:
# This library support linux only.