[package]
  ref = "12.4.0.76"

[[build_configs]]
  pattern = "aarch64-linux*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnvjpeg/linux-aarch64/libnvjpeg-linux-aarch64-12.4.0.76-archive.tar.xz"

[[build_configs]]
  pattern = "x86_64-linux*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnvjpeg/linux-x86_64/libnvjpeg-linux-x86_64-12.4.0.76-archive.tar.xz"

[[build_configs]]
  pattern = "x86_64-windows*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnvjpeg/windows-x86_64/libnvjpeg-windows-x86_64-12.4.0.76-archive.zip"
