[package]
  ref = "575.57.08"

[[build_configs]]
  pattern = "x86_64-linux*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnvidia_nscq/linux-x86_64/libnvidia_nscq-linux-x86_64-575.57.08-archive.tar.xz"
