[package]
url = "https://github.com/libvips/libvips.git"
ref = "v8.16.1"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "meson"
patches = ["fix_build_error.patch"]
dependencies = ["libexpat@2.7.1", "libjpeg@9f"]
dev_dependencies = ["pkgconf@2.4.3"]
