[package]
url = "https://bitbucket.org/multicoreware/x265_git.git"
ref = "4.1"
depth = 1
src_dir = "source"

[[build_configs]]
build_system = "cmake"
options = [
    "-DENABLE_ASSEMBLY=OFF",
    "-DCMAKE_EXE_LINKER_FLAGS=-ldl",
    "-DCMAKE_SHARED_LINKER_FLAGS=-ldl"
]
