[package]
  url = "https://dev.gentoo.org/~blueness/eudev/eudev-3.2.10.tar.gz"
  ref = "3.2.10"
  depth = 1

[[build_configs]]
  system_name = "linux"
  build_system = "makefiles"
  dev_dependencies = ["gperf@3.1"]

# Note:
# This library support linux only.