[package]
url = "https://github.com/google/clspv.git"
ref = "main"
depth = 1

[[build_configs]]
build_system = "cmake"
dependencies = [
    "llvm@15.0.7",
    "spirv-headers@1.4.313.0",
    "spirv-tools@2025.1",
]
options = [
    "-DCLSPV_BUILD_TESTS=OFF",
    "-DCLSPV_LLVM_BINARY_DIR=${DEPS_DIR}",
    "-DSPIRV_HEADERS_SOURCE_DIR=${BUILDTREES_DIR}/spirv-headers@1.4.313.0/src",
    "-DSPIRV_TOOLS_SOURCE_DIR=${BUILDTREES_DIR}/spirv-tools@2025.1/src",
    "-DCLSPV_LLVM_SOURCE_DIR=${BUILDTREES_DIR}/llvm@15.0.7/src/llvm",
    "-DCLSPV_CLANG_SOURCE_DIR=${BUILDTREES_DIR}/llvm@15.0.7/src/clang",
    "-DCLSPV_EXTERNAL_LIBCLC_DIR=${BUILDTREES_DIR}/llvm@15.0.7/src/libclc",
]