[package]
url = "https://archive.mesa3d.org/mesa-23.2.1.tar.xz"
ref = "23.2.1"

[[build_configs]]
pattern = "*linux*"
build_system = "meson"
dependencies = [
    "glproto@1.4.14",
    "dri2proto@2.8",
    "libxshmfence@1.3.3",
    "openssl@1.1.1w",
    "libexpat@2.7.1",
    "libdrm@2.4.124",
    "zlib@1.3.1",
    "libxcb@1.17.0",
    "libx11@1.8.11",
    "libxext@1.3.6",
    "libxfixes@6.0.1",
    "libxdamage@1.1.6",
    "libunwind@1.6.1",
    "libglvnd@1.7.0",
    "libxxf86vm@1.1.6",
    "libxrandr@1.5.4",
    "glslang@1.4.335.0",
]
dev_dependencies = [
    "macros@1.20.2",
    "pkgconf@2.4.3"
]
options = [
]
# Note:
# This library support linux only.