[package]
url = "https://ftp.gnu.org/gnu/libtasn1/libtasn1-v4.20.0-src.tar.gz"
ref = "v4.20.0"
depth = 1

[[build_configs]]
build_system = "makefiles"
dev_dependencies = ["bison@3.8.2"]
pre_configure = ["./bootstrap"]
