[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxrandr.git"
ref = "libXrandr-1.5.4"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
dependencies = ["libxext@1.3.6", "libxrender@0.9.12"]
dev_dependencies = ["macros@1.20.2"]
envs = ["NOCONFIGURE=1"]
pre_configure = ["./autogen.sh"]

# Note:
# This library support linux only.