[package]
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/libclc-19.1.7.src.tar.xz"
ref = "19.1.7"
depth = 1

[[build_configs]]
build_system = "cmake"
dependencies = ["spirv-llvm-translator@15.0.7"]
dev_dependencies = ["spirv-tools@2025.1"]
