[package]
url = "https://github.com/google/glog.git"
ref = "v0.6.0"
depth = 1

[[build_configs]]
build_system = "cmake"
dependencies = ["gflags@2.2.2"]
options = [
	"-DBUILD_TESTING=OFF",
	"-DWITH_GTEST=OFF",
	"-DBUILD_EXAMPLES=OFF",
	"-DWITH_SYMBOLIZE=OFF",
]
