[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxfixes.git"
ref = "libXfixes-6.0.1"
depth = 1

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["libx11@1.8.11"]
dev_dependencies = ["macros@1.20.2"]

# Note:
# This library support linux only.