[package]
  url = "https://invisible-island.net/archives/byacc/byacc-20241231.tgz"
  ref = "20241231"
  build_tool = true

[[build_configs]]
  pattern = "*linux*"
  build_system = "makefiles"
  build_shared = "_"
  post_install = ["ln -sf ${PACKAGE_DIR}/bin/yacc ${PACKAGE_DIR}/bin/byacc"]
