[package]
  url = "https://invisible-island.net/archives/byacc/byacc-20241231.tgz"
  ref = "20241231"
  native = true

[[build_configs]]
  build_system = "makefiles"
  post_install = ["ln -sf ${PACKAGE_DIR}/bin/yacc ${PACKAGE_DIR}/bin/byacc"]
