[package]
url = "https://mirrors.tuna.tsinghua.edu.cn/gnu/libtool/libtool-2.5.4.tar.xz"
ref = "2.5.4"
depth = 1
supported_hosts = ["linux", "darwin"]

[[build_configs]]
build_system = "makefiles"
dev_dependencies = ["m4@1.4.19"]