[package]
  url = "https://gitlab.freedesktop.org/xorg/proto/glproto.git"
  ref = "glproto-1.4.17"
  depth = 1

# ============== build for aarch64-linux ============== #
[[build_configs]]
  system_name = "linux"
  system_processor = "aarch64"
  build_system = "makefiles"
  dev_dependencies = ["macros@1.20.2"]
  envs = ["NOCONFIGURE=1"]
  pre_configure = ["./autogen.sh"]
  options = ["--host=arm-linux"]

# ============== build for x86_64-linux ============== #
[[build_configs]]
  system_name = "linux"
  system_processor = "x86_64"
  build_system = "makefiles"
  dev_dependencies = ["macros@1.20.2"]
  envs = ["NOCONFIGURE=1"]
  pre_configure = ["./autogen.sh"]
  options = ["--host=x86_64-linux"]

# Note:
# This library support linux only.