[package]
  ref = "590.44.01_cuda13.1"

[[build_configs]]
  pattern = "x86_64-linux*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/cuda_compat/linux-x86_64/cuda_compat-linux-x86_64-590.44.01_cuda13.1-archive.tar.xz"
