[package]
  ref = "12.9.40580548"

[[build_configs]]
  pattern = "aarch64-linux*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/cuda_compat/linux-aarch64/cuda_compat-linux-aarch64-12.9.40580548-archive.tar.xz"
