[package]
url = "https://github.com/opencv/opencv.git"
ref = "4.11.0"

[[build_configs]]
build_system = "cmake"
dependencies = [
    "opencv_contrib@4.11.0",
]
options = [
    "-DOPENCV_EXTRA_MODULES_PATH=${BUILDTREES_DIR}/opencv_contrib@4.11.0/src/modules",
    "-DBUILD_LIST=calib3d,core,features2d,flann,highgui,imgcodecs,imgproc,xfeatures2d,aruco,video,videoio,objdetect,tracking,ccalib,stereo",
    "-DBUILD_TESTING=OFF",
    "-DBUILD_DOCS=OFF",
    "-DBUILD_ANDROID_EXAMPLES=OFF",
    "-DBUILD_EXAMPLES=OFF",
    "-DBUILD_PERF_TESTS=OFF",
    "-DBUILD_TESTS=OFF",
]
