[package]
url = "https://xcb.freedesktop.org/dist/xcb-util-renderutil-0.3.10.tar.xz"
ref = "0.3.10"

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
dependencies = ["libxcb@1.17.0"]
dev_dependencies = ["macros@1.20.2", "libtool@2.5.4", "pkgconf@2.4.3"]

# Note:
# This library support linux only.