[package]
url = "https://github.com/KhronosGroup/SPIRV-Tools.git"
ref = "v2025.1"
depth = 1

[[build_configs]]
pattern = "*linux*"
build_system = "cmake"
dependencies = ["spirv-headers@1.4.313.0"]
options = ["-DSPIRV-Headers_SOURCE_DIR=${DEPS_DIR}"]

# Note:
# This library support linux only.