[package]
ref = "21.1.4"

[[build_configs]]
pattern = "x86_64-linux*"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.4/LLVM-21.1.4-Linux-X64.tar.xz"
build_system = "prebuilt"

[[build_configs]]
pattern = "aarch64-linux*"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.4/LLVM-21.1.4-Linux-ARM64.tar.xz"
build_system = "prebuilt"