[package]
url = "_"
ref = "12.9.1"

# =============== build for aarch64-linux ============ #

[[build_configs]]
pattern = "aarch64-linux*"
build_system = "nobuild"
dependencies = [
  "cuda_compat@12.9.40580548",
  "cuda_cudart@12.9.79",
  "cuda_nvrtc@12.9.86",
  "cuda_nvtx@12.9.79",
  "libcublas@12.9.1.4",
  "libcudla@12.9.19",
  "libcufft@11.4.1.4",
  "libcufile@1.14.1.1",
  "libcurand@10.3.10.19",
  "libcusolver@11.7.5.82",
  "libcusparse@12.5.10.65",
  "libnpp@12.4.1.87",
  "cuda_cupti@12.9.79",
  "cuda_nvml_dev@12.9.79",
  "cuda_profiler_api@12.9.79",
  "cuda_nvvp@12.9.79",
  "cuda_cccl@12.9.27",
  "nvidia_fs@2.25.7",
  "cuda_documentation@12.9.88",
  "cuda_nvcc@12.9.86",
  "cuda_nvprune@12.9.82",
  "cuda_cuobjdump@12.9.82",
  "cuda_cuxxfilt@12.9.82",
  "cuda_nvdisasm@12.9.88",
  "cuda_sanitizer_api@12.9.79",
  "cuda_nvprof@12.9.79",
  "nsight_compute@2025.2.1.3",
]

# =============== build for x86_64-linux ============ #

[[build_configs]]
pattern = "x86_64-linux*"
build_system = "nobuild"
dependencies = [
  "cuda_cudart@12.9.79",
  "cuda_nvrtc@12.9.86",
  "cuda_nvtx@12.9.79",
  "libcublas@12.9.1.4",
  "libcufft@11.4.1.4",
  "libcufile@1.14.1.1",
  "libcurand@10.3.10.19",
  "libcusolver@11.7.5.82",
  "libcusparse@12.5.10.65",
  "libnpp@12.4.1.87",
  "libnvjpeg@12.4.0.76",
  "cuda_cupti@12.9.79",
  "cuda_nvml_dev@12.9.79",
  "cuda_profiler_api@12.9.79",
  "cuda_nvvp@12.9.79",
  "cuda_cccl@12.9.27",
  "libnvidia_nscq@575.57.08",
  "nvidia_driver@575.57.08",
  "nvidia_fs@2.25.7",
  "fabricmanager@575.57.08",  # server required only
  "cuda_documentation@12.9.88",
  "cuda_nvcc@12.9.86",
  "cuda_nvprune@12.9.82",
  "cuda_cuobjdump@12.9.82",
  "cuda_cuxxfilt@12.9.82",
  "cuda_nvdisasm@12.9.88",
  "cuda_sanitizer_api@12.9.79",
  "cuda_nvprof@12.9.79",
  "nsight_compute@2025.2.1.3",
]

# =============== build for x86_64-windows ============ #

[[build_configs]]
pattern = "x86_64-windows*"
build_system = "nobuild"
dependencies = [
  "cuda_cudart@12.9.79",
  "cuda_nvrtc@12.9.86",
  "cuda_nvtx@12.9.79",
  "libcublas@12.9.1.4",
  "libcufft@11.4.1.4",
  "libcurand@10.3.10.19",
  "libcusolver@11.7.5.82",
  "libcusparse@12.5.10.65",
  "libnpp@12.4.1.87",
  "libnvjpeg@12.4.0.76",
  "cuda_cupti@12.9.79",        # analysis performance
  "cuda_nvml_dev@12.9.79",     # used to monitor gpu
  "cuda_profiler_api@12.9.79",
  "cuda_nvvp@12.9.79",
  "cuda_cccl@12.9.27",
  "cuda_documentation@12.9.88",
  "cuda_nvcc@12.9.86",
  "cuda_nvprune@12.9.82",
  "cuda_cuobjdump@12.9.82",
  "cuda_cuxxfilt@12.9.82",
  "cuda_nvdisasm@12.9.88",
  "cuda_sanitizer_api@12.9.79",
  "cuda_nvprof@12.9.79",
  "nsight_compute@2025.2.1.3",
  "nsight_vse@2025.2.1.25125",
  "nsight_systems@2025.1.3.140",
  "cuda_demo_suite@12.9.79",
  "visual_studio_integration@12.9.79"
]
