[package]
  url = "https://github.com/log4cplus/log4cplus.git"
  ref = "REL_2_0_8"
  depth = 1

[[build_configs]]
  build_system = "cmake"
  options = [
    "-DWITH_UNIT_TESTS=OFF",
    "-DLOG4CPLUS_BUILD_TESTING=OFF",
    "-DLOG4CPLUS_BUILD_LOGGINGSERVER=OFF",
    "-DLOG4CPLUS_ENABLE_THREAD_POOL=OFF",
    "-DLOG4CPLUS_SINGLE_THREADED=ON"
  ]