[package]
  ref = "12.9.82"

[[build_configs]]
  pattern = "aarch64-linux*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnvfatbin/linux-aarch64/libnvfatbin-linux-aarch64-12.9.82-archive.tar.xz"

[[build_configs]]
  pattern = "x86_64-linux*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnvfatbin/linux-x86_64/libnvfatbin-linux-x86_64-12.9.82-archive.tar.xz"

[[build_configs]]
  pattern = "x86_64-windows*"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnvfatbin/windows-x86_64/libnvfatbin-windows-x86_64-12.9.82-archive.zip"
