[package]
url = "git://git.savannah.gnu.org/readline.git"
ref = "readline-8.2"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "makefiles"

# Note:
# This library support linux only.