[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxdamage.git"
ref = "libXdamage-1.1.6"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
dependencies = [
    "libunwind@1.6.1",
    "libx11@1.8.11",
    "libxfixes@6.0.1",
]
dev_dependencies = ["macros@1.20.2"]
envs = ["NOCONFIGURE=1"]
pre_configure = ["./autogen.sh"]

# Note:
# This library support linux only.