[package]
url = "https://github.com/util-linux/util-linux.git"
ref = "v2.41"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
dependencies = ["sqlite3@3.49.0"]
envs = ["NOCONFIGURE=1"]
dev_dependencies = [
    "autoconf@2.72",
    "gettext@0.25",
    "flex@2.6.4",
    "bison@3.8.2",
    "libtool@2.5.4",
]
pre_configure = ["./autogen.sh"]
options = [
    "--without-python",
    "--without-ncurses",
    "--disable-makeinstall-chown",
    "--without-systemdsystemunitdir",
    "--disable-bash-completion",
]

# Note:
# This library support linux only.
