[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxcb.git"
ref = "libxcb-1.17.0"
depth = 1

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["libxau@1.0.12", "xcb-proto@1.17.0"]
dev_dependencies = ["macros@1.20.2"]
envs = ["NOCONFIGURE=1"]
pre_configure = ["./autogen.sh"]

# Note:
# This library support linux only.
