[package]
url = "https://gitlab.freedesktop.org/xorg/proto/glproto.git"
ref = "glproto-1.4.17"
depth = 1

# ============== build for aarch64-Linux ============== #
[[build_configs]]
pattern = "aarch64-linux*"
build_system = "makefiles"
dev_dependencies = ["macros@1.20.2"]

# ============== build for x86_64-linux ============== #
[[build_configs]]
pattern = "x86_64-linux*"
build_system = "makefiles"
dev_dependencies = ["macros@1.20.2"]

# Note:
# This library support linux only.