[package]
  url = "https://github.com/Distrotech/help2man.git"
  ref = "master"
  depth = 1

[[build_configs]]
  system_name = "linux"
  build_system = "makefiles"

# Note:
# This library support linux only.