[package]
url = "https://mirrors.tuna.tsinghua.edu.cn/gnu/m4/m4-1.4.19.tar.xz"
ref = "1.4.19"
supported_hosts = ["linux", "darwin"]

[[build_configs]]
build_system = "makefiles"
build_shared = "no"
build_static = "no"
