[package]
url = "https://github.com/llvm/llvm-project.git"
ref = "llvmorg-15.0.7"
depth = 1
src_dir = "llvm"

[[build_configs]]
build_system = "cmake"
options = [
    "-DLLVM_ENABLE_PROJECTS='clang'",
    "-DLLVM_TARGETS_TO_BUILD='X86;AMDGPU'",
    "-DLLVM_BUILD_LLVM_DYLIB=ON",
    "-DLLVM_ENABLE_RTTI=ON",
    "-DLLVM_ENABLE_ASSERTIONS=OFF"
]

# Extra options:
# LLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;mlir;compiler-rt