[package]
url = "https://www.x.org/releases/individual/xcb/xcb-util-image-0.4.1.tar.xz"
ref = "0.4.1"

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
dev_dependencies = ["macros@1.20.2", "automake@1.18", "libtool@2.5.4"]

# Note:
# This library support linux only.