[package]
url = "https://github.com/madler/zlib.git"
ref = "v1.3.1"

[[build_configs]]
build_system = "cmake"
options = ["-DZLIB_BUILD_EXAMPLES=OFF"]
post_install_windows = [
  "cmake -E rename ${PACKAGE_DIR}/lib/zlib.lib ${PACKAGE_DIR}/lib/z.lib",
]