[package]
url = "https://mirrors.tuna.tsinghua.edu.cn/gnu/ncurses/ncurses-6.5.tar.gz"
ref = "6.5"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
build_shared = "--with-shared"
options = [
    "--disable-stripping",
    "--with-termlib",
    "--disable-widec"
]

# Note:
# This library support linux only.
