[package]
url = "https://github.com/netwide-assembler/nasm.git"
ref = "nasm-2.16.03"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
build_shared = "_"
build_static = "_"
patches = ["fix_install.patch"]
build_in_source = true
dev_dependencies = ["automake@1.18", "libtool@2.5.4"]
envs = ["NOCONFIGURE=1"]
pre_configure = ["./autogen.sh"]

[[build_configs]]
system_name = "windows"
system_processor = "x86_64"
url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-win64.zip"
build_system = "prebuilt"
post_install = [
    "cmake -E make_directory ${PACKAGE_DIR}/bin",
    "cmake -E rename ${PACKAGE_DIR}/nasm.exe ${PACKAGE_DIR}/bin/nasm.exe",
    "cmake -E rename ${PACKAGE_DIR}/ndisasm.exe ${PACKAGE_DIR}/bin/ndisasm.exe"
]
