[package]
url = "https://github.com/KhronosGroup/SPIRV-Headers.git"
ref = "vulkan-sdk-1.4.313.0"
depth = 1

[[build_configs]]
pattern = "*linux*"
build_system = "cmake"

# Note:
# This library support linux only.