[package]
  ref = "11.8.0.86"

[[build_configs]]
  system_name = "linux"
  system_processor = "aarch64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnpp/linux-aarch64/libnpp-linux-aarch64-11.8.0.86-archive.tar.xz"

[[build_configs]]
  system_name = "linux"
  system_processor = "x86_64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnpp/linux-x86_64/libnpp-linux-x86_64-11.8.0.86-archive.tar.xz"

[[build_configs]]
  system_name = "windows"
  system_processor = "x86_64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libnpp/windows-x86_64/libnpp-windows-x86_64-11.8.0.86-archive.zip"