[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver.git"
ref = "libXScrnSaver-1.2.4"
depth = 1

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["libxext@1.3.6"]
dev_dependencies = ["macros@1.20.2", "pkgconf@2.4.3"]

# Note:
# This library support linux only.
