[package]
url = "https://github.com/gflags/gflags.git"
ref = "v2.2.2"
depth = 1

[[build_configs]]
build_system = "cmake"
options = [
    "-DBUILD_SHARED_LIBS=ON",
    "-DBUILD_STATIC_LIBS=OFF",
    "-DBUILD_TESTING=OFF",
]
