[package]
  url = "https://gitlab.freedesktop.org/xorg/lib/libpciaccess.git"
  ref = "libpciaccess-0.18.1"
  depth = 1

[[build_configs]]
  system_name = "linux"
  build_system = "meson"
  dependencies = ["zlib@1.3.1"]

# Note:
# This library support linux only.