[package]
  url = "https://github.com/google/leveldb.git"
  ref = "1.23"
  depth = 1

[[build_configs]]
  build_system = "cmake"
  options = [
    "-DLEVELDB_BUILD_TESTS=OFF",
    "-DLEVELDB_BUILD_BENCHMARKS=OFF"
  ]