[package]
ref = "17.0.6"

[[build_configs]]
pattern = "x86_64-linux*"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz"
build_system = "prebuilt"

[[build_configs]]
pattern = "aarch64-linux*"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-aarch64-linux-gnu.tar.xz"
build_system = "prebuilt"