[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxmu.git"
ref = "libXmu-1.2.1"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
dev_dependencies = ["macros@1.20.2"]
envs = ["NOCONFIGURE=1"]
pre_configure = ["./autogen.sh"]

# Note:
# This library support linux only.