[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxcursor.git"
ref = "libXcursor-1.2.3"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
dependencies = [
    "xorgproto@2024.1",
    "libx11@1.8.11",
    "libxfixes@6.0.1",
    "libxrender@0.9.12",
]
dev_dependencies = ["macros@1.20.2"]
envs = ["NOCONFIGURE=1"]
pre_configure = ["./autogen.sh"]

# Note:
# This library support linux only.
