[package]
url = "https://gitlab.freedesktop.org/libbsd/libbsd.git"
ref = "0.12.2"
depth = 1
supported_hosts = ["linux", "darwin"]

[[build_configs]]
build_system = "makefiles"
pre_configure = ["cd ${REPO_DIR} && ${REPO_DIR}/autogen"]
dependencies = ["libmd@1.1.0"]