
[package]
url = "https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.9.tar.bz2"
ref = "1.2.9"

[[build_configs]]
system_name = "linux"
build_system = "makefiles"

# Note:
# This library support linux only.