[package]
url = "https://ftp.gnu.org/pub/gnu/autoconf/autoconf-2.72.tar.xz"
ref = "2.72"
supported_hosts = ["linux", "darwin"]

[[build_configs]]
build_system = "makefiles"
dev_dependencies = ["m4@1.4.19"]