[package]
url = "https://gitlab.freedesktop.org/libbsd/libbsd.git"
ref = "0.12.2"
depth = 1
supported_hosts = ["linux", "darwin"]

[[build_configs]]
build_system = "makefiles"
dependencies = ["libmd@1.1.0"]
envs = ["NOCONFIGURE=1"]
pre_configure = ["${REPO_DIR}/autogen"]