[package]
url = "https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz"
ref = "3.8.2"

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
dev_dependencies = ["m4@1.4.19"]

# Note:
# This library support linux only.