[package]
url = "https://github.com/KhronosGroup/glslang.git"
ref = "vulkan-sdk-1.4.335.0"
depth = 1

[[build_configs]]
build_system = "cmake"
dependencies = ["spirv-tools@1.4.335.0"]
options = ["-DALLOW_EXTERNAL_SPIRV_TOOLS=ON"]
