[package]
  url = "https://gitlab.gnome.org/GNOME/glib.git"
  ref = "2.84.1"
  depth = 1

[[build_configs]]
  pattern = "*linux*"
  build_system = "meson"
  build_tools = ["python3:setuptools"]
  options = ["-Dlibmount=enabled"]
  dependencies = ["util-linux@2.41", "zlib@1.3.1"]
  dev_dependencies = ["pkgconf@2.4.3"]
