[package]
  url = "https://github.com/AprilRobotics/apriltag.git"
  ref = "v3.4.3"
  depth = 1

[[build_configs]]
  build_system = "cmake"
  options = ["-DBUILD_EXAMPLES=OFF", "-DBUILD_PYTHON_WRAPPER=OFF"]
