[package]
  url = "https://github.com/ChaiScript/ChaiScript.git"
  ref = "v6.1.0"
  depth = 1

[[build_configs]]
  build_system = "cmake"
  cxx_standard = "c++17"
  patches = ["fix-msvc-chrono.patch"]