[package]
url = "https://mirrors.tuna.tsinghua.edu.cn/gnu/automake/automake-1.18.tar.xz"
ref = "1.18"
supported_hosts = ["linux", "darwin"]

[[build_configs]]
build_system = "makefiles"
dev_dependencies = ["autoconf@2.72"]