[package]
url = "https://ftp.gnu.org/gnu/automake/automake-1.18.tar.xz"
ref = "1.18"
build_tool = true

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dev_dependencies = ["autoconf@2.72"]