[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxi.git"
ref = "libXi-1.8.2"
depth = 1

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
envs = ["xorg_cv_malloc0_returns_null=yes"]
dependencies = ["libxext@1.3.6", "xorg-sgml-doctools@1.12.1", "libxfixes@6.0.1"]
dev_dependencies = ["macros@1.20.2"]
options = ["--disable-docs"]

# Note:
# This library support linux only.
