[package]
url = "https://xcb.freedesktop.org/dist/xcb-proto-1.17.0.tar.xz"
ref = "1.17.0"

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
build_tools = ["python3"]
envs = ["PYTHON3_PATH=${PYTHON3_PATH}"]
dev_dependencies = ["macros@1.20.2"]

# Note:
# This library support linux only.