[package]
  ref = "12.9.19"

[[build_configs]]
  system_name = "linux"
  system_processor = "aarch64"
  build_system = "prebuilt"
  url = "https://developer.download.nvidia.cn/compute/cuda/redist/libcudla/linux-aarch64/libcudla-linux-aarch64-12.9.19-archive.tar.xz"
