namespace = "FFmpeg"

[linux]
[[linux_components]]
component = "avutil"
filename = "libavutil.so.55"
dependencies = []

[[linux_components]]
component = "avcodec"
filename = "libavcodec.so.57"
dependencies = ["avutil"]

[[linux_components]]
component = "avdevice"
filename = "libavdevice.so.57"
dependencies = ["avformat", "avutil"]

[[linux_components]]
component = "avfilter"
filename = "libavfilter.so.6"
dependencies = ["swscale", "swresample"]

[[linux_components]]
component = "avformat"
filename = "libavformat.so.57"
dependencies = ["avcodec", "avutil"]

[[linux_components]]
component = "postproc"
filename = "libpostproc.so.54"
dependencies = ["avcodec", "swscale", "avutil"]

[[linux_components]]
component = "swresample"
filename = "libswresample.so.2"
dependencies = ["avcodec", "swscale", "avutil", "avformat"]

[[linux_components]]
component = "swscale"
filename = "libswscale.so.4"
dependencies = ["avcodec", "avutil", "avformat"]

[windows]
[[windows_components]]
component = "avutil"
filename = "avutil.lib"
dependencies = []

[[windows_components]]
component = "avcodec"
filename = "avcodec.lib"
dependencies = ["avutil"]

[[windows_components]]
component = "avdevice"
filename = "avdevice.lib"
dependencies = ["avformat", "avutil"]

[[windows_components]]
component = "avfilter"
filename = "avfilter.lib"
dependencies = ["swscale", "swresample"]

[[windows_components]]
component = "avformat"
filename = "avformat.lib"
dependencies = ["avcodec", "avutil"]

[[windows_components]]
component = "postproc"
filename = "postproc.lib"
dependencies = ["avcodec", "swscale", "avutil"]

[[windows_components]]
component = "swresample"
filename = "swresample.lib"
dependencies = ["avcodec", "swscale", "avutil", "avformat"]

[[windows_components]]
component = "swscale"
filename = "swscale.lib"
dependencies = ["avcodec", "avutil", "avformat"]