[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxtrans.git"
ref = "xtrans-1.5.2"
depth = 1

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
patches = ["fix_autogen.patch"]
dependencies = ["xorg-sgml-doctools@1.12.1"]
dev_dependencies = [
    "macros@1.20.2",
    "pkgconf@2.4.3"
]
envs = ["NOCONFIGURE=1"]
pre_configure = ["./autogen.sh"]

# Note:
# This library support linux only.
