[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git"
ref = "xcb-util-0.4.1"
depth = 1

[[build_configs]]
system_name = "linux"
build_system = "makefiles"
patches = ["fix_submodule_url.sh"]
dependencies = ["libxcb@1.17.0"]
dev_dependencies = ["macros@1.20.2", "libtool@2.5.4"]
envs = ["NOCONFIGURE=1"]
pre_configure = ["./autogen.sh"]

# Note:
# This library support linux only.
